pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    
    
    stages{
        stage("maven"){
            steps{
            sh 'mvn clean'
            sh 'mvn validate'
            sh 'mvn compile'
            sh 'mvn install'
            sh 'mvn test'   
            sh 'mvn package'         
            }
 
        }

        stage("Upload artifact to JFrog"){
            steps{
                sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
                target/bio*.jar \
                "http://ec2-54-167-127-179.compute-1.amazonaws.com:8081/artifactory/geosolution/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
}